from enum import Enum
class Direction(Enum):
    UP = 0
    RIGHT = 1
    DOWN = 2
    LEFT = 3

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_COLOR = "black"

PLAYER_WIDTH = 50
PLAYER_HEIGHT = 50
PlAYER_X_CENTER = SCREEN_WIDTH / 2 - PLAYER_WIDTH / 2
PLAYER_Y_CENTER = SCREEN_HEIGHT / 2 - PLAYER_HEIGHT / 2
PLAYER_VELOCITY = 250
PLAYER_COLOR = "white"
